version: "3.5"
name: chatnet-integration-tests
services:
  server:
    container_name: dotnet
    depends_on:
      - postgres
      - mongo
      - redis
    build:
      context: ./server/Chat.NET
      dockerfile: ./Web/Dockerfile
    volumes:
      - ~/.aspnet/https:/https
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - REDIS_CONNECTION_STRING=redis
    env_file:
      - test.env
    ports:
      - 5000:80
  
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  redis:
    container_name: redis
    image: redis/redis-stack
    volumes:
      - ./redis/:/data redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001